plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ric.preset'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ric.preset'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '0.3.0'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main.assets.srcDirs += ["${rootDir}/presets"]
    }
}
